name: Build saint-x kernel

on:
  push:
    branches: 'saint-x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: SantriKode/AnyKranul3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Saint-x-V.1.0
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: rosy-perf_defconfig
        image: Image.gz-dtb
