name: Releases tags

on: 
  push:
    tags:
    - 'Saint-perf-V1.1'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.SAINT_EX }}
        bodyFile: "body.md"
        tag: "Saint-perf-V1.1"
